### ISSUE TITLE
Backend API implementation status

### ISSUE THREAD

**Issue by trinhdn97** [kardiachain/kardia-explorer-backend#11]
# Description

- [X] GetBlockList: /blocks
- [X] GetLatestTxs: /txs
- [X] GetTransactionsOfBlock: /block/:block/txs
- [X] GetTransactionByHash: /txs/:txHash
- [x] GetBalance: /addresses/:address/balance
- [X] GetNodeInfo: /nodes
- [X] GetValidatorsList: /validators
- [X] GetBlockByHashOrHeight: /block/:block
- [X] TxsByAddress: /addresses/:address/txs

To be updated

# Current issues

- [ ] Fix tx status and parse receipt logs (will be resolved after get receipts process is improved)
- [x] Skip in some APIs

# Todo
- [ ] API Documentation
